sudo: required
language: generic

services:
  - docker


before_install:
  - docker build -t aortiz/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true aortiz/docker-react npm run test